### ISSUE TITLE
Font weight in title bar does not follow the user's choice

### ISSUE THREAD

**Issue by fthx** [ubuntu/communitheme#312] opened 2018-04-03 20:20 UTC
Hi,

Using Liberation or Ubuntu (e.g.) Bold fonts in Tweaks section Window Title, I get different font weight in CSD or non-CSD title bars : 
- bold in non-CSD ;
- regular in CSD.

It does not happen in Ambiance or Materia themes, e.g.

**Comment by Feichtmeier** [comment] 2018-04-20 20:14
Could you attach two screenshots? I am not sure if I understand you correctly

**Comment by clobrano** [comment] 2018-06-02 16:18
This is more than a month old bug with "info-needed" lable. I think we need a policy to drop bugs in this state after some time.

**Comment by fthx** [comment] 2018-06-02 16:47
![image](https://user-images.githubusercontent.com/23138504/40878717-61d9cc62-6695-11e8-9321-4d2e0ef14fc8.png)

![image](https://user-images.githubusercontent.com/23138504/40878732-738d5104-6695-11e8-9ff5-bf623a0a74d4.png)

**Comment by clobrano** [comment] 2018-07-08 09:12
This is reproducible on Adwaita and Ambiance as well. It seems that "Window Title" affects only titlebars and not headerbars

![image](https://user-images.githubusercontent.com/2883614/42418376-a10fece2-829f-11e8-9de8-ac9cbc13904e.png)
![image](https://user-images.githubusercontent.com/2883614/42418382-d4285f4c-829f-11e8-8e3b-89aabd3eb708.png)

**Comment by fthx** [comment] 2018-07-08 11:43
The difference is that Communitheme does use non-bold font with CSD ?
So the Communitheme design is to use non-bold or bold window title ?

**Comment by clobrano** [comment] 2018-07-08 12:01
There isn't anything communitheme specific. In Gnome you can change only the titlebar font (the ones in the windows out of focus in my pictures)
Headerbars (like in settings, tweaks and all new gnome applications) do not allow changing their font

**Comment by fthx** [comment] 2018-07-08 12:11
There is something Communitheme specific : when I choose non-bold font for window title, Adwaita, Ambiance and Materia do show a bold font in CSD headerbars ; Arc and Communitheme do show a non-bold font in CSD headerbars. So headerbars do allow in some way to change their font (weight ?)

So if the design is to have non-bold window titles and CSD headerbars, all is ok. If not, the Communitheme behaviour is not right.

**Comment by clobrano** [comment] 2018-07-08 19:04
> So if the design is to have non-bold window titles and CSD headerbars

Do you always have non-bold windows titles in headerbars? In my machine I always have bold font in headerbars, that's what I am saying

**Comment by fthx** [comment] 2018-07-08 19:13
Oh yes I do always have non-bold font in CSD headerbar with Communitheme. In non-CSD windows titles, I get what I choose in Tweaks.
Maybe related : I do use gtk-communitheme via the PPA, I do not use the gnome-shell theme.

**Comment by clobrano** [comment] 2018-07-08 20:47
Ok that's the main problem. As far as I know, PPA is not updated, please [remove the ppa](https://launchpad.net/ppa-purge) and [install the snap package](https://github.com/ubuntu/communitheme-snap-helpers/blob/master/README.md)

**Comment by fthx** [comment] 2018-07-09 06:48
Seems that the PPA *is* updated as the package is daily updated and I can see some changes. (?)
So anyway I installed the snap ; you know that the snap does not allow to use gtk-communitheme outside of the gnome-shell communitheme session. It does not fit my needs, but that's another point.

Well, I started the communitheme session, selected the communitheme gtk theme and here I am : 

![image](https://user-images.githubusercontent.com/23138504/42434709-6ec0e11e-8354-11e8-8cf7-77e331973a25.png)

It seems that the title is bold only for some apps, maybe related to GTK2 ones ? In the most part, I get non-bold titles, i do not get the same appearance as yours.

**Comment by clobrano** [comment] 2018-07-09 06:56
> It seems that the title is bold only for some apps, maybe related to GTK2 ones ?

In my clean VM that uses snap, Libreoffice title is bold as well. Is it possible that your machine kept some misconfiguration from ppa?

**Comment by fthx** [comment] 2018-07-09 07:32
Well, I really don't know what config could remain from the PPA. I do use Bionic, is something different in Cosmic ?

**Comment by clobrano** [comment] 2018-07-09 07:44
I really don't know either, I use Bionic as well. I can suggest you to double check gdconf, since your settings look like mine when I change the titlebar font (either with tweak or gdconf)

**Comment by Feichtmeier** [comment] 2018-07-21 09:09
@fthx Could you just install everything in a VM and double check if this happens too? If not we can close this for sure.

**Comment by fthx** [comment] 2018-07-21 09:34
Oh it works fine running the snap on a clean install in VM. The point is that this odd behaviour (that I get on two different laptops with two Bionic, one clean install and one updated from Artful) does not append running some other GTK themes (Adwaita, e.g.).
If the GTK communitheme is not intended to be used outside of the Shell communitheme, there is no issue. Otherwise there's something strange.

**Comment by clobrano** [comment] 2018-07-21 12:06
Just double checked to be sure:

- You can select communitheme theme on a Ubuntu session
- In both sessions headerbars have always bold fonts, no matter what font you choose, while titlebars follow font selection in tweak

**Closed** 2018-07-21 14:42 UTC
Labels: not-reproducible, upstream
